"""Update role column to use Enum type

Revision ID: 4a488fcde778
Revises: dd0c646addcd
Create Date: 2026-04-15 15:50:19.359619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '4a488fcde778'
down_revision: Union[str, Sequence[str], None] = 'dd0c646addcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = set(inspector.get_table_names())

    def has_table(table_name: str) -> bool:
        return table_name in tables

    def has_constraint(table_name: str, constraint_name: str) -> bool:
        return any(
            c["name"] == constraint_name
            for c in inspector.get_unique_constraints(table_name)
        )

    def has_index(table_name: str, index_name: str) -> bool:
        return any(i["name"] == index_name for i in inspector.get_indexes(table_name))

    if has_table("grn_documents"):
        if has_constraint("grn_documents", op.f("grn_documents_po_id_key")):
            op.drop_constraint(op.f("grn_documents_po_id_key"), "grn_documents", type_="unique")
        if has_index("grn_documents", op.f("ix_grn_documents_po_id")):
            op.drop_index(op.f("ix_grn_documents_po_id"), table_name="grn_documents")
        op.create_index(op.f("ix_grn_documents_po_id"), "grn_documents", ["po_id"], unique=True)

    if has_table("purchase_orders"):
        if has_constraint("purchase_orders", op.f("purchase_orders_po_number_key")):
            op.drop_constraint(op.f("purchase_orders_po_number_key"), "purchase_orders", type_="unique")
        if has_constraint("purchase_orders", op.f("purchase_orders_pr_id_key")):
            op.drop_constraint(op.f("purchase_orders_pr_id_key"), "purchase_orders", type_="unique")
        if has_index("purchase_orders", op.f("ix_purchase_orders_po_number")):
            op.drop_index(op.f("ix_purchase_orders_po_number"), table_name="purchase_orders")
        op.create_index(op.f("ix_purchase_orders_po_number"), "purchase_orders", ["po_number"], unique=True)
        if has_index("purchase_orders", op.f("ix_purchase_orders_pr_id")):
            op.drop_index(op.f("ix_purchase_orders_pr_id"), table_name="purchase_orders")
        op.create_index(op.f("ix_purchase_orders_pr_id"), "purchase_orders", ["pr_id"], unique=True)

    if has_table("purchase_requisitions"):
        if has_constraint("purchase_requisitions", op.f("purchase_requisitions_pr_number_key")):
            op.drop_constraint(
                op.f("purchase_requisitions_pr_number_key"),
                "purchase_requisitions",
                type_="unique",
            )
        if has_index("purchase_requisitions", op.f("ix_purchase_requisitions_pr_number")):
            op.drop_index(op.f("ix_purchase_requisitions_pr_number"), table_name="purchase_requisitions")
        op.create_index(
            op.f("ix_purchase_requisitions_pr_number"),
            "purchase_requisitions",
            ["pr_number"],
            unique=True,
        )

    if has_table("users"):
        op.execute(
            sa.text(
                "UPDATE users SET role = UPPER(role) "
                "WHERE role IS NOT NULL AND role != UPPER(role)"
            )
        )
        op.alter_column(
            "users",
            "role",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Enum("ADMIN", "REQUESTER", name="userrole", native_enum=False),
            existing_nullable=False,
            existing_server_default=sa.text("'requester'::character varying"),
        )
        if has_constraint("users", op.f("users_email_key")):
            op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
        if has_index("users", op.f("ix_users_email")):
            op.drop_index(op.f("ix_users_email"), table_name="users")
        op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'REQUESTER', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'requester'::character varying"))
    op.drop_index(op.f('ix_purchase_requisitions_pr_number'), table_name='purchase_requisitions')
    op.create_index(op.f('ix_purchase_requisitions_pr_number'), 'purchase_requisitions', ['pr_number'], unique=False)
    op.create_unique_constraint(op.f('purchase_requisitions_pr_number_key'), 'purchase_requisitions', ['pr_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_purchase_orders_pr_id'), table_name='purchase_orders')
    op.create_index(op.f('ix_purchase_orders_pr_id'), 'purchase_orders', ['pr_id'], unique=False)
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=False)
    op.create_unique_constraint(op.f('purchase_orders_pr_id_key'), 'purchase_orders', ['pr_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('purchase_orders_po_number_key'), 'purchase_orders', ['po_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_grn_documents_po_id'), table_name='grn_documents')
    op.create_index(op.f('ix_grn_documents_po_id'), 'grn_documents', ['po_id'], unique=False)
    op.create_unique_constraint(op.f('grn_documents_po_id_key'), 'grn_documents', ['po_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
